{% set name = "azure-macro-utils-c" %}
{% set version = "2022.08.09" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/Azure/macro-utils-c/archive/3cddd3dbe44c16f0043731dc93419e24bf16c8a8.zip
    sha256: 2b10da08ecf66967d19598223b6fb1fd9586f40b7a52edf1ddacf60276ffcacd

build:
  number: 2
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make   # [not win]
    - ninja  # [win]

test:
  commands:
    - if not exist %LIBRARY_PREFIX%\\include\\macro_utils\\macro_utils.h exit 1  # [win]
    - test -f "${PREFIX}/include/macro_utils/macro_utils.h"  # [not win]

about:
  home: https://github.com/Azure/azure-macro-utils-c
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: |
    Microsoft Azure IoT SDKs - macro utils for C

extra:
  recipe-maintainers:
    - xylar
    - seanyen
